#! /bin/sh

case "$1" in
    start)
        echo "Starting AESD Socket Server"
        start-stop-daemon -S -n aesdsocket -x /usr/bin/aesdsocket -- -d
        ;;
    stop)
        echo "Stopping AESD Socket Server"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "usage: $0 {start | stop}"
    exit 1
esac
exit 0
